name: Staging Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    # (Same as the QA Testing Workflow)

  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS Staging Server
        run: |
          # Your deployment commands for staging here

      - name: Send Email Notification on Failure
        if: failure()
        run: |
          # Your email notification script for failure

      - name: Send Email Notification on Success
        if: success()
        run: |
          # Your email notification script for success
